name: env_snap
channels:
  - terradue
  - conda-forge
  - defaults
dependencies:
  - snap=8.0.0
  - lxml
  - affine=2.3.0
  - alabaster=0.7.12
  - appdirs=1.4.4
  - argh=0.26.2
  - arrow=1.2.2
  - astroid=2.6.6
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - autopep8=1.5.6
  - babel=2.9.1
  - backcall=0.2.0
  - bcrypt=3.2.0
  - binaryornot=0.4.4
  - black=19.3b0
  - bleach=4.1.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2021.5.30
  - cffi=1.14.6
  - cfitsio=3.470
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cookiecutter=1.7.3
  - cryptography=35.0.0
  - curl=7.82.0
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.3.0
  - dataclasses=0.8
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - docutils=0.17.1
  - entrypoints=0.3
  - expat=2.4.8
  - fiona=1.8.4
  - flake8=3.9.0
  - flasgger=0.9.5
  - flask=2.0.3
  - freetype=2.10.4
  - freexl=1.0.6
  - future=0.18.2
  - gdal=2.3.3
  - geojson=2.5.0
  - geomet=0.3.0
  - geopandas=0.6.1
  - geos=3.7.1
  - gettext=0.19.8.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - hdf4=4.2.13
  - hdf5=1.10.4
  - html2text
  - icu=58.2
  - idna=3.3
  - imagecodecs-lite=2019.12.3
  - imageio=2.13.1
  - imagesize=1.3.0
  - importlib-metadata=4.8.1
  - inflection=0.5.1
  - intel-openmp=2022.0.0
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - itsdangerous=2.0.1
  - jedi=0.17.2
  - jinja2=3.0.3
  - jinja2-time=0.2.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=7.1.2
  - jupyter_core=4.8.1
  - jupyterlab_pygments
  - kealib=1.4.7
  - keyring=23.1.0
  - kiwisolver=1.3.1
  - krb5=1.16.4
  - lazy-object-proxy=1.6.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libffi=3.4.2
  - libgdal=2.3.3
  - libglib=2.68.4
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.6.2
  - libpng=1.6.37
  - libpq=11.5
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.10.0
  - libtiff=4.2.0
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - markupsafe=2.0.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2022.0.0
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - networkx=2.5
  - numpy=1.19.5
  - numpydoc=1.1.0
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1p
  - packaging=21.3
  - pandas=1.1.5
  - pandoc=2.12
  - pandocfilters=1.5.0
  - paramiko=2.8.1
  - parso=0.7.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.2
  - pluggy=1.0.0
  - poppler=0.67.0
  - poppler-data=0.4.11
  - postgresql=11.5
  - poyo=0.5.0
  - proj4=5.2.0
  - prompt-toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycodestyle=2.6.0
  - pycparser=2.21
  - pycurl=7.44.1
  - pydocstyle=6.1.1
  - pyflakes=2.2.0
  - pygments=2.11.2
  - pylint=2.9.6
  - pyls-black=0.4.6
  - pyls-spyder=0.3.2
  - pynacl=1.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.6.13
  - python-dateutil=2.8.2
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.36.2
  - python-slugify=5.0.2
  - python_abi=3.6
  - pytz=2021.3
  - pywavelets=1.1.1
  - pywin32=228
  - pywin32-ctypes=0.2.0
  - pyyaml=5.4.1
  - pyzmq=22.2.1
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.9.7
  - qtawesome=1.0.3
  - qtconsole=5.2.2
  - qtpy=2.0.1
  - rasterio=1.0.21
  - requests=2.27.1
  - rope=0.22.0
  - rtree=0.9.7
  - schedule=1.1.0
  - scikit-image=0.17.2
  - scipy=1.5.3
  - sentinelsat=1.1.1
  - setuptools=58.0.4
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.16.0
  - snowballstemmer=2.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sphinx=4.4.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.0.5
  - spyder-kernels=2.0.5
  - sqlite=3.38.2
  - tbb=2021.5.0
  - testpath=0.5.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - three-merge=0.1.1
  - tifffile=2020.6.3
  - tinycss=0.4
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.11.2
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=4.3.3
  - typed-ast=1.4.3
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - ujson=4.0.2
  - unidecode=1.2.0
  - urllib3=1.26.8
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - watchdog=2.1.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.3
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.12.1
  - xerces-c=3.2.2
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
